CREATE TABLE "crexi_active_listings" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"property_link" text,
	"property_name" text,
	"property_status" text,
	"type" text,
	"address" text,
	"city" text,
	"state" text,
	"zip" text,
	"tenants" text,
	"lease_term" text,
	"remaining_term" text,
	"sqft" double precision,
	"lot_size" text,
	"units" double precision,
	"price_per_unit" double precision,
	"noi" double precision,
	"cap_rate" double precision,
	"asking_price" double precision,
	"price_per_sqft" double precision,
	"price_per_acre" double precision,
	"days_on_market" double precision,
	"opportunity_zone" text,
	"longitude" double precision,
	"latitude" double precision,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "crexi_comps_records" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"property_link" text,
	"property_name" text,
	"property_type" text,
	"apn" text,
	"address" text,
	"unit" text,
	"city" text,
	"zip_code" text,
	"state" text,
	"county" text,
	"sale_date" text,
	"sold_price" double precision,
	"lease_signed" text,
	"lease_rate" text,
	"lender" text,
	"loan_amount" double precision,
	"loan_type" text,
	"interest_rate" double precision,
	"financing_maturity_date" text,
	"zoning_code" text,
	"opportunity_zone" text,
	"water_code" text,
	"sewer_code" text,
	"building_sqft" double precision,
	"number_of_units" double precision,
	"number_of_addresses" double precision,
	"building_count" double precision,
	"number_of_stories" double precision,
	"year_built" double precision,
	"lot_size_acres" double precision,
	"lot_size_sqft" double precision,
	"asking_cap_rate" double precision,
	"closing_noi" double precision,
	"closing_cap_rate" double precision,
	"sold_price_per_sqft" double precision,
	"sold_price_per_acre" double precision,
	"occupancy" text,
	"lease_type" text,
	"lease_commencement" text,
	"lease_term" text,
	"lease_term_remaining" text,
	"lease_expiration_date" text,
	"rent_bumps" text,
	"lease_options" text,
	"tenants" text,
	"days_on_market" double precision,
	"latitude" double precision,
	"longitude" double precision,
	"usps_vacancy" text,
	"usps_vacancy_date" text,
	"parcel_value_type" text,
	"improvement_value" double precision,
	"land_value" double precision,
	"total_parcel_value" double precision,
	"tax_year" double precision,
	"annual_tax_bill" double precision,
	"pfc_recording_date" text,
	"pfc_indicator" text,
	"pfc_document_type" text,
	"reo_sale_flag" text,
	"transaction_event_type" text,
	"owner_name" text,
	"mailing_address" text,
	"mailing_address_unit" text,
	"mailing_address_city" text,
	"mailing_address_state" text,
	"mailing_address_zip_code" text,
	"mailing_address_care_of" text,
	"created_at" timestamp with time zone DEFAULT now()
);