name: Dagster+ Deploy

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod-deploy:
    name: Dagster+ Production Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          organization_id: openmidmarket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  branch-deploy:
    name: Dagster+ Branch Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: dagster-io/dagster-cloud-action/actions/serverless_branch_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          organization_id: openmidmarket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  branch-cleanup:
    name: Dagster+ Branch Cleanup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: dagster-io/dagster-cloud-action/actions/serverless_branch_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          organization_id: openmidmarket
          action: teardown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
