-- Store Historical OM PDFs scraped from Crexi property-record detail pages.
--
-- Derivation:
-- - Candidate rows are those whose latest raw_json has source.isCrexiOm = true.
-- - The source asset id comes from raw_json.crexiSalesAssetIds[0].
-- - om_url is the S3 URL after downloading
--   https://api.crexi.com/assets/{asset_id}/offering-memorandum with the
--   short-lived access token generated by the authenticated Crexi detail page.
-- - attachment_urls stores the non-tokenized source endpoint, S3 URL, asset id,
--   and "Historical OM" description.

ALTER TABLE public.crexi_api_comps
    ADD COLUMN IF NOT EXISTS om_url text,
    ADD COLUMN IF NOT EXISTS attachment_urls jsonb NOT NULL DEFAULT '[]'::jsonb;
